---
- hosts: localhost
  vars_files:
    - ../vars/vars.yml
  tasks:

    - name: Create Stream
      shell: |
        aws kinesis create-stream \
                    --stream-name "{{ aws_kinesis_stream_name }}" \
                      --shard-count "{{ aws_kinesis_shard_count }}" \
                        --region "{{ aws_region_id }}"

      register: command_result  
      failed_when: command_result.rc >= 2

    # - debug:
    #     msg: "{{ command_result }}"
