---
- hosts: localhost
  vars_files:
    - ../vars/vars.yml
  tasks:

    - name: Describe Stream
      shell: |
        aws kinesis describe-stream --stream-name "{{ aws_kinesis_stream_name }}"
      register: command_result  
      failed_when: command_result.rc >= 2

    - debug:
        msg: "{{ command_result }}"
